### ISSUE TITLE
broken on node 12

### ISSUE THREAD

**Issue by skeet70** [thlorenz/irish-pub#16]
```
λ irish-pub
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/home/mumu/.nvm/versions/node/v12.0.0/lib/node_modules/irish-pub/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/mumu/.nvm/versions/node/v12.0.0/lib/node_modules/irish-pub/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/mumu/.nvm/versions/node/v12.0.0/lib/node_modules/irish-pub/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

Looks like there's an issue with `graceful-fs` by way of `tar` on Node 12. I tried updating on my fork but it looks like `tar` is now on version 4 and readable-stream is on version 3. Wasn't confident those breaking changes weren't relevant. Might still open a PR but opening this issue anyway.

**Comment by vweevers** [comment]
I replaced `tar` with `tar-stream` in [my fork](https://github.com/vweevers/canadian-pub): https://github.com/vweevers/canadian-pub/commit/55b7cca7aaed49a9fbedee21f5eff1cdc12ab233
